# Workflow to build and promote a container image.
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - '**'
      - .github/workflows/build-image.yaml
  push:
    branches:
      - main
    paths:
      - '**'
      - .github/workflows/build-image.yaml

name: Image Build And Promote

jobs:
  build:
    name: Build
    uses: Bandwidth/docker-release-workflow/.github/workflows/docker-release-workflow.yml@v2
    with:
      registry: "bandwidth-docker.jfrog.io"
      image-name: "argocd-image-updater"
      image-namespace: "platform"
      cache-from: type=registry,ref=bandwidth-docker.jfrog.io/platform/argocd-image-updater:cache
      cache-to: type=registry,ref=bandwidth-docker.jfrog.io/platform/argocd-image-updater:cache,mode=max